# Generated by Django 2.2.3 on 2021-05-15 10:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost_price', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('bakeryitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.BakeryItem')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Ingredient')),
            ],
            options={
                'db_table': 'ingredient_bakeryitem_ingredients',
            },
        ),
        migrations.AddField(
            model_name='bakeryitem',
            name='ingredients',
            field=models.ManyToManyField(through='data.IngredientRatio', to='data.Ingredient'),
        ),
    ]
